### ISSUE TITLE
Not Connecting to Minecraft Client

### ISSUE THREAD

**Issue by Wylx-32k** [Chit132/abyss-overlay#26]
No errors or anything, it just doesnt connect to the Minecraft Client(lunar). No music commands work, it doesnt auto /who when its toggled. Basically doesnt do anything.

**Comment by Cryptizism** [comment]
Can we please talk in #support on the [abyss overlay discord](https://discord.gg/abyssoverlay) if the below does not help 
We don't really deal with issues on the GitHub but I might aswell do it since we are here.

Music is known to not work, Chit, the maker of the overlay, is on a break due to school and other things so will probably not get seen to in awhile. Nobody else has access to the bot or the music stuff.

Auto-who is completely experimental at the moment as displayed beside it so if you join the discord and tell us ur issue we would be glad to help.

[This ](https://cdn.discordapp.com/attachments/822659322453950544/995985698031157368/Abyss_Overlay_Setup_v1.6.2_x64.exe)experimental version should fix the lunar bug you are facing

**Comment by Cryptizism** [comment]
If you cannot access support via the discord please reopen this issue, for the best and fastest response please use the discord
