### ISSUE TITLE
Can you see the overlay made by myself XD.

### ISSUE THREAD

**Issue by IAFEnvoy** [Chit132/abyss-overlay#29]
I'm sorry to bother you, but can you see my own overlay?

https://github.com/IAFEnvoy/StarburstOverlay

It provides a overall searcher and more game mode. I think we can merge together.

See the README for more details.

**Comment by Nodo08** [comment]
> I'm sorry to bother you, but can you see my own overlay?
> 
> https://github.com/IAFEnvoy/StarburstOverlay
> 
> It provides a overall searcher and more game mode. I think we can merge together.
> 
> See the README for more details.

It is kind of you to ask, but I'm afraid at the time being I can't give you an exact response. The overlay is originally created and maintained by Chit, with the support of Crypt&Blue for coding and multiple of our hardworking community helpers in our discord server. The overlay had always been considered one of the lightweight overlays for chill and casual bedwars players. I do agree that having the various interesting features of your overlay, the overlay would be more complete as a whole and such. The decision is up to our two main devs, whether or not they want to merge with you (I notice the UI being incredibly similar). Crypt had a plan of rewriting the entire overlay for a while now, but since Chit had been busy with school none of us was able to deliver anything. The translating project was also delayed to a state of almost dropped off as of now. I would notify both of them about your ideas and keep this Issue opened. 
Be sure to join our discord server, discord.gg/abyssoverlay, thank you for reaching out and we hope to be speaking with you soon.
哈哈

**Comment by Cryptizism** [comment]
Hey, I'll take care of this for now!
Please get in touch with me at Cryptizism#2999 or if not possible Cryptizism@gmail.com so we can discuss this further
Thanks!

**Comment by Cryptizism** [comment]
Just going to bump this

**Comment by IAFEnvoy** [comment]
Ok My Discord id is IAFEnvoy#1454
