### ISSUE TITLE
Feature Suggestion: Atlauncher support

### ISSUE THREAD

**Issue by Atvaster** [Chit132/abyss-overlay#31]
Atlauncher is a multiple instance forge, fabric, and vanilla modloader. It would be cool if you could add abyss to it, although it would require a way to select specific instances of atlauncher.

**Comment by Nodo08** [comment]
Hi Atvaster!
Upon looking up ATLauncher, I find it being very similar to MultiMC/ManyMC or simply any of those launchers that support multiple instances all in one, that you play on the instance with your configured settings for each. Sadly I am afraid we can't simply just "add" another new individual button that instantly selects the correct log file of the instance automatically. That is, the case of adding an entire new button apart from the other sources directing to your log file of the game. However though, if you just want the overlay working with your instance it can be easily done by selecting the correct log file in your .minecraft folder which should be there for each instance. Hope this helped, and have a great day.

For more questions regarding the issue you can reply to this message, or join our discord server for assistance.
discord.gg/abyssoverlay
*Also note that I kept mentioning "I" instead of "we". This is mainly the reason I'm still not fully considered into the staff team of the overlay in any form, hence addressing the question as a personal view. I notified the actual staff team about your Issue request but the reply from them will probably be the same as mine.

**Comment by Cryptizism** [comment]
Hey, admin here!

I think that there isn't a reason to add a specific client to the splash screen of the overlay as there are a plethora of multi-instance minecraft launchers and we just don't want the first thing you see to be jam packed with information. 
However, I believe we should advertise better the ability to put your own custom log with possible help as well. If you think my judgement is unfair please let me know so we can better consider! 

Thanks!

**Comment by Cryptizism** [comment]
closing due to stale issue, reopen if u wish to argue against my judgement
