### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by buiawpkgew1** [Chit132/abyss-overlay#7]
Why not open the source code

**Comment by Cryptizism** [comment]
I think it's due to private apis to get calls such as the custom tags and start up the music sessions. Chit to my last known knowledge has plans to make it open source in the future he just wants to make it as clean as possible beforehand. Also Chit tends to like doing things himself so he may just keep it closed source to make sure he's the only one touching it. There is also the aspect of revenue because if he open sources the software everyone can get the paid perks on their side which makes him lose money. 

I also advise you do not use the Github issues to asks questions but rather go to the discord which can be found in the overlays top left corner.

**Comment by buiawpkgew1** [comment]
Sorry i can't get up to discord
对不起 我上不去discord
